<?php

    namespace app\modules\backend\api;

    use app\modules\backend\api\models\admin\Admin;
    use umono\multiple\controllers\AdminController;
    use Yii;

    /**
     * Class Controller
     *
     * @property Admin $identity
     * @method Admin getIdentity()
     * @package app\modules\admin\api
     */
    abstract class Controller extends AdminController
    {
        public function init()
        {
            parent::init(); // TODO: Change the autogenerated stub
            $this->get   = $this->handlerGetParam();
            $this->param = Yii::$app->request->getBodyParams() ?? '';
        }

        public function getClientId()
        {
            return \Yii::$app->getRequest()->getHeaders()->get('X-Client-Id', '');
        }

        public function freeAuth(): array
        {
            return [
                'auth/login',
                'test/*'
            ];
        }
    }
