<?php

    namespace app\modules\api\base;

    use Yii;
    use yii\web\UnauthorizedHttpException;

    abstract class Controller extends \umono\multiple\controllers\ApiController
    {
        /**
         * @throws \yii\base\InvalidConfigException
         */
        public function init()
        {
            parent::init(); // TODO: Change the autogenerated stub
            $this->get = $this->handlerGetParam();
            $access    = \Yii::$app->request->headers['yaa-access-token'];
            if (!empty($access)) {
                $this->user = '';// TODO user数据处理
            }

            if (!Yii::$app->request->isGet) {
                $this->param = Yii::$app->request->getBodyParams() ?? '';
            }
        }

        /**
         * @throws UnauthorizedHttpException
         */
        public function isAuth()
        {
            if (empty($this->user_id)) {
                throw new UnauthorizedHttpException('请登录后重试');
            }
        }
    }